### ISSUE TITLE
Compiled firmware for flashing

### ISSUE THREAD

**Issue by NOSSUDAK** [MotorDynamicsLab/encoder-tracker#2]
It would be nice if a compiled firmware file (in .hex format)  for the Farmduino project is available here. It could be used for flashing the STM32 MCU used in Farmduino board. Thanks in advance.

**Comment by cneshi** [comment]
> It would be nice if a compiled firmware file (in .hex format) for the Farmduino project is available here. It could be used for flashing the STM32 MCU used in Farmduino board. Thanks in advance.

Hi there, we've created a [release](https://github.com/MotorDynamicsLab/encoder-tracker/releases) with an attached binary for your use. Thanks for the reminder.
